### ISSUE TITLE
getMODIS_data download only 4.6 kB 

### ISSUE THREAD

**Issue by gustavoveloso** [16EAGLE/getSpatialData#51]
I try to download images from the MODIS satellite (MODIS_MYD09GA_V6), but when I apply the getMODIS_data command I only get a 4.6 kb file. The true full database has on average 50 mb.
Sorry my english.

Thanks in advance,

**Comment by MLezamaValdes** [comment]
Hi, I have the same problem, but it started only recently. I downloaded some scenes already using  getMODIS_data and they are all right (from 16th of Jan 2020), if I now repeat the process I get 11kB hdfs (before 3MB) and HDF View reports this to be an unsupported file format, while the scene previously downloaded opens perfectly fine.. Also downloading this very scene from earthExplorer works without problems. Do you have any idea what's the issue here? Thank you!

**Comment by gustavoveloso** [comment]
I can solve the problem.
Just create two variables (username and password) with name and password the login_USGS before running getMODIS_data.
Example:
login_USGS(username  = "myname",password = "mynamepassword")


username = myname
password = mynamepassword
getMODIS_data (********)
I can download the images

Sorry for my terrible english

**Comment by MLezamaValdes** [comment]
Thank you for your reply, but I'm already doing this, so it doesn't solve my problem, unfortunately..

**Comment by gustavoveloso** [comment]
Can you send the scritp that is having problems to test it?

**Comment by MLezamaValdes** [comment]
Hi! this is what I do in my script. But as it used to work like this I think the problem must lie somewhere else... 

login_USGS("username", "password")
dirpath <- "mydirpath"
set_archive(dirpath)
aoi <- readOGR(paste0(dirpath, "aoi.shp"))
set_aoi(aoi)
time_range <- c("2019-02-01", "2019-02-01")
product1 <- "MODIS_MOD11_L2_V6"
q <- getMODIS_query(time_range = time_range, name = product1, aoi=get_aoi()) 
files <-  getMODIS_data(q)

[aoi.zip](https://github.com/16EAGLE/getSpatialData/files/4180084/aoi.zip)

Cheers

**Comment by gustavoveloso** [comment]
Hello
I get a palliative solution for your script.
It will only work to download modis data.

On my computer to download the set of data required in your script

#--------------------------------------------------------------
library(httr)

login_USGS("username", "password")
dirpath <- "mydirpath"
set_archive(dirpath)
aoi <- readOGR(paste0(dirpath, "aoi.shp"))
set_aoi(aoi)
time_range <- c("2019-02-01", "2019-02-01")
product1 <- "MODIS_MOD11_L2_V6"
q <- getMODIS_query(time_range = time_range, name = product1, aoi=get_aoi())

username  = "username"
password = "password"
httr::GET("https://ladsweb.modaps.eosdis.nasa.gov/archive/allData/6/MOD11_L2/2019/032/MOD11_L2.A2019032.0055.006.2019033083748.hdf",httr::authenticate(username, password) , silent = T)

files <- getMODIS_data(q)

#--------------------------------------------------------------

best regards

**Comment by MLezamaValdes** [comment]
oh great, that works! thank you so much! :) 
Sorry for responding so late..

**Comment by 16EAGLE** [comment]
This issue should be resolved with the latest major release. Please consider reinstalling. You can find a list of all changes that were applied here: http://jxsw.de/getSpatialData/news/index.html#getspatialdata-0-1-0

The reason for this bug was a recently added authentication requirement for LAAD DAAC files, which had been openly available before.

You now need to call both the newly added function `login_earthdata()` with your NASA Earthdata URS credentials and `login_USGS()` with your USGS ERS credentials before querying and downloading MODIS data using `getSpatialData`. Please let me know if you encounter any issues.

**Comment by chloewright** [comment]
Hi! I am still having this issue. I have downloaded the 0.1.0 version of this package (R version 4.0.2) and logged in successfully using login_earthdata() and login_USGS(). However, getMODIS_data() is only downloading MODIS files (MODIS_MOD13Q1_V6) that are 12KB and can't be read by get_subdatasets

Thanks in advance for any help!

**Comment by 16EAGLE** [comment]
Hi, could you please provide me with an reproducible example (aoi, time range, your query) that produces the issue so that I can trace the reason on my end? Otherwise its hard for me to isolate the reason

**Comment by chloewright** [comment]
Oh sorry, here it is!

[AreaOfInterest.zip](https://github.com/16EAGLE/getSpatialData/files/4881806/AreaOfInterest.zip)


library(getSpatialData)
library(sf)
library(sp)


#read in region of interest
roi_big <- st_read("AreaOfInterest.gpkg")
roi_sp <- as(roi_big, "Spatial")

#login info
login_earthdata("username", "password")
login_USGS("username", "password")

TimeRange <- c("2018-04-06", "2018-06-30") 

#get records
modServerResponse  <- getMODIS_records(
  time_range = TimeRange,
  products = "MODIS_MOD13Q1_V6",
  aoi = roi_sp
)

#download
modisDownloaded <- getMODIS_data(modServerResponse, 
                                 dir_out = "E:/directory")

Session Info:

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sp_1.4-2             sf_0.9-4             getSpatialData_0.1.0

**Comment by 16EAGLE** [comment]
Thanks for the code. Unfortunately, I was not able to reproduce the error – for me, your code works fine:

```R
modisDownloaded <- getMODIS_data(modServerResponse, dir_out = "tmp/")
#> Column 'download_available' not present, calling check_availabilty() to check download availability of records...
#> Receiving MD5 checksums...
#> Assembling dataset URLs...
#> [Dataset 1/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018081.h10v03.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018081.h10v03.006.2018097234502.hdf'...
#> |==================================================================================| 100%
#> [Dataset 2/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018081.h10v04.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018081.h10v04.006.2018097234642.hdf'...
#> |==================================================================================| 100%
#> [Dataset 3/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018097.h10v04.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018097.h10v04.006.2018113234021.hdf'...
#> |==================================================================================| 100%
#> [Dataset 4/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018097.h10v03.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018097.h10v03.006.2018113234900.hdf'...
#> |==================================================================================| 100%
#> [Dataset 5/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018113.h10v04.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018113.h10v04.006.2018129234616.hdf'...
#> |==================================================================================| 100%
#> [Dataset 6/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018113.h10v03.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018113.h10v03.006.2018130000816.hdf'...
#> |==================================================================================| 100%
#> [Dataset 7/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018129.h10v03.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018129.h10v03.006.2018151110850.hdf'...
#> |==================================================================================| 100%
#> [Dataset 8/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018129.h10v04.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018129.h10v04.006.2018151110647.hdf'...
#> |==================================================================================| 100%
#> [Dataset 9/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018145.h10v04.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018145.h10v04.006.2018162000930.hdf'...
#> |==================================================================================| 100%
#> [Dataset 10/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018145.h10v03.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018145.h10v03.006.2018162001612.hdf'...
#> |==================================================================================| 100%
#> [Dataset 11/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018161.h10v04.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018161.h10v04.006.2018177235445.hdf'...
#> |==================================================================================| 100%
#> [Dataset 12/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018161.h10v03.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018161.h10v03.006.2018177235721.hdf'...
#> |==================================================================================| 100%
#> [Dataset 13/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018177.h10v04.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018177.h10v04.006.2018197102816.hdf'...
#> |==================================================================================| 100%
#> [Dataset 14/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018177.h10v03.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018177.h10v03.006.2018197103303.hdf'...
#> |==================================================================================| 100%
#> Columns added to records: 'download_available', 'order_status', 'md5_checksum', 'dataset_url', 'dataset_file'
```

The files do have the assumed sizes and can be opened:

![Screenshot-20200707105624-628x364](https://user-images.githubusercontent.com/23257860/86754266-0d7e2700-c041-11ea-9035-d1af8bfab702.png)

Some ideas, since I am not sure what is causing the issue on your end: Maybe the issue is related to your Earthdata account. Can you confirm whether logging in at `https://urs.earthdata.nasa.gov/` works without issues? Under Applications > Authorized Apps, do you see LAADS? Can you login at `https://ladsweb.modaps.eosdis.nasa.gov/` via your Earthdata account?

After doing this, can you rerun your download query and see whether it works?

Also, can you provide me one of these 12KB files that you get?

**Comment by 16EAGLE** [comment]
Thanks for the code. Unfortunately, I was not able to reproduce the error – for me, your code works fine:

```R
modisDownloaded <- getMODIS_data(modServerResponse, dir_out = "tmp/")
#> Column 'download_available' not present, calling check_availabilty() to check download availability of records...
#> Receiving MD5 checksums...
#> Assembling dataset URLs...
#> [Dataset 1/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018081.h10v03.006' to '/home/jas24ny/Documents/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018081.h10v03.006.2018097234502.hdf'...
#> |==================================================================================| 100%
#> [Dataset 2/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018081.h10v04.006' to '/home/xxxxxx/xxxxxx/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018081.h10v04.006.2018097234642.hdf'...
#> |==================================================================================| 100%
#> [Dataset 3/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018097.h10v04.006' to '/home/xxxxxx/xxxxxx/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018097.h10v04.006.2018113234021.hdf'...
#> |==================================================================================| 100%
#> [Dataset 4/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018097.h10v03.006' to '/home/xxxxxx/xxxxxx/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018097.h10v03.006.2018113234900.hdf'...
#> |==================================================================================| 100%
#> [Dataset 5/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018113.h10v04.006' to '/home/xxxxxx/xxxxxx/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018113.h10v04.006.2018129234616.hdf'...
#> |==================================================================================| 100%
#> [Dataset 6/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018113.h10v03.006' to '/home/xxxxxx/xxxxxx/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018113.h10v03.006.2018130000816.hdf'...
#> |==================================================================================| 100%
#> [Dataset 7/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018129.h10v03.006' to '/home/xxxxxx/xxxxxx/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018129.h10v03.006.2018151110850.hdf'...
#> |==================================================================================| 100%
#> [Dataset 8/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018129.h10v04.006' to '/home/xxxxxx/xxxxxx/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018129.h10v04.006.2018151110647.hdf'...
#> |==================================================================================| 100%
#> [Dataset 9/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018145.h10v04.006' to '/home/xxxxxx/xxxxxx/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018145.h10v04.006.2018162000930.hdf'...
#> |==================================================================================| 100%
#> [Dataset 10/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018145.h10v03.006' to '/home/xxxxxx/xxxxxx/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018145.h10v03.006.2018162001612.hdf'...
#> |==================================================================================| 100%
#> [Dataset 11/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018161.h10v04.006' to '/home/xxxxxx/xxxxxx/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018161.h10v04.006.2018177235445.hdf'...
#> |==================================================================================| 100%
#> [Dataset 12/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018161.h10v03.006' to '/home/xxxxxx/xxxxxx/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018161.h10v03.006.2018177235721.hdf'...
#> |==================================================================================| 100%
#> [Dataset 13/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018177.h10v04.006' to '/home/xxxxxx/xxxxxx/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018177.h10v04.006.2018197102816.hdf'...
#> |==================================================================================| 100%
#> [Dataset 14/14 | File 1/1] Downloading dataset 'MOD13Q1.A2018177.h10v03.006' to '/home/xxxxxx/xxxxxx/tmp//MODIS_MOD13Q1_V6//MOD13Q1.A2018177.h10v03.006.2018197103303.hdf'...
#> |==================================================================================| 100%
#> Columns added to records: 'download_available', 'order_status', 'md5_checksum', 'dataset_url', 'dataset_file'
```

The files do have the assumed sizes and can be opened:

![Screenshot-20200707105624-628x364](https://user-images.githubusercontent.com/23257860/86754266-0d7e2700-c041-11ea-9035-d1af8bfab702.png)

Some ideas, since I am not sure what is causing the issue on your end: Maybe the issue is related to your Earthdata account. Can you confirm whether logging in at `https://urs.earthdata.nasa.gov/` works without issues? Under Applications > Authorized Apps, do you see LAADS? Can you login at `https://ladsweb.modaps.eosdis.nasa.gov/` via your Earthdata account?

After doing this, can you rerun your download query and see whether it works?

Also, can you provide me one of these 12KB files that you get?

**Comment by chloewright** [comment]
I figured out what the issue was - I had the wrong login info for my Earthdata account. However it appears that no matter what you type into login_earthdata() it always returns that the login was successful, even when you have the wrong username and password 

![Error](https://user-images.githubusercontent.com/32311994/86816851-30a4d880-c039-11ea-8e43-73047c341db6.PNG)

Thanks for your help and sorry for not double checking my credentials before posting!

**Comment by 16EAGLE** [comment]
Thanks for catching this! This should be fixed with the latest commit so that `login_earthdata` throws an error when credentials are wrong.
